name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - master  # or anther branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Use the version of .NET Core 

      - name: Restore
        run: dotnet restore ./Reservations.sln

      - name: Build
        run: dotnet build ./Reservations.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Reservations.sln --configuration Release --no-build
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0  # Use a newer version
        with:
          server: ${{ secrets.MONSTERASP_FTP_SERVER }}
          username: ${{ secrets.MONSTERASP_FTP_USERNAME }}
          password: ${{ secrets.MONSTERASP_FTP_PASSWORD }}
          local-dir: ./output/
          server-dir: ${{ secrets.MONSTERASP_FTP_PATH }}
          protocol: ftps  # Use `ftps` to ensure a secure FTP connection
